#!/usr/bin/env ruby

# Variables

AWS_REGION = 'us-east-1'

DEV_AWS_ACCESS_KEY_ID = ENV['DEV_AWS_ACCESS_KEY_ID']
DEV_AWS_SECRET_ACCESS_KEY = ENV['DEV_AWS_SECRET_ACCESS_KEY']
DEV_AWS_ACCOUNT_ID = ENV['DEV_AWS_ACCOUNT_ID']

SANDBOX_AWS_ACCESS_KEY_ID = ENV['SANDBOX_AWS_ACCESS_KEY_ID']
SANDBOX_AWS_SECRET_ACCESS_KEY = ENV['SANDBOX_AWS_SECRET_ACCESS_KEY']
SANDBOX_AWS_ACCOUNT_ID = ENV['SANDBOX_AWS_ACCOUNT_ID']
