#!/usr/bin/env ruby

# Variables

AWS_REGION = 'us-east-1'

SOURCE_AWS_ACCESS_KEY_ID = ENV['DEV_AWS_ACCESS_KEY_ID']
SOURCE_AWS_SECRET_ACCESS_KEY = ENV['DEV_AWS_SECRET_ACCESS_KEY']
SOURCE_AWS_ACCOUNT_ID = ENV['DEV_AWS_ACCOUNT_ID']

TARGET_AWS_ACCESS_KEY_ID = ENV['SANDBOX_AWS_ACCESS_KEY_ID']
TARGET_AWS_SECRET_ACCESS_KEY = ENV['SANDBOX_AWS_SECRET_ACCESS_KEY']
TARGET_AWS_ACCOUNT_ID = ENV['SANDBOX_AWS_ACCOUNT_ID']

#in case we need to use postgre_sql params
#TARGET_RDS_HOSTNAME = ENV['SANDBOX_RDS_HOSTNAME']
#TARGET_RDS_PORT = ENV['SANDBOX_RDS_PORT']

#rds params
TARGET_RDS_INSTANCE_ID = ENV['SANDBOX_RDS_INSTANCE_ID']
TARGET_RDS_DB_NAME = ENV['SANDBOX_RDS_DB_NAME']
TARGET_RDS_USER = ENV['SANDBOX_RDS_USER']
TARGET_RDS_PWD = ENV['SANDBOX_RDS_PWD']
TARGET_PRINCIPAL_USER_ARN = ENV['SANDBOX_PRINCIPAL_USER_ARN']
TARGET_VPC_ARN = ENV['SANDBOX_VPC_ARN']

