#!/usr/bin/env ruby

# Variables

AWS_REGION = 'us-east-1'

SOURCE_AWS_ACCESS_KEY_ID = ENV['DEV_AWS_ACCESS_KEY_ID']
SOURCE_AWS_SECRET_ACCESS_KEY = ENV['DEV_AWS_SECRET_ACCESS_KEY']
SOURCE_AWS_ACCOUNT_ID = ENV['DEV_AWS_ACCOUNT_ID']

TARGET_AWS_ACCESS_KEY_ID = ENV['SANDBOX_AWS_ACCESS_KEY_ID']
TARGET_AWS_SECRET_ACCESS_KEY = ENV['SANDBOX_AWS_SECRET_ACCESS_KEY']
TARGET_AWS_ACCOUNT_ID = ENV['SANDBOX_AWS_ACCOUNT_ID']
